In [6]:
from PIL import Image
import numpy as np
import torch
image = np.array(Image.open("images/papillon.jpg"))[:, :, 0]

In [7]:
b, c, a = 2, 3, 4
array_3d = np.random.rand(b, c, a)  # Replace with your actual 3D array
B = np.random.rand(a)  # Replace with your actual array B

# Calculate the argmax along the last axis
argmax_indices = np.argmax(array_3d, axis=2)

# Use the argmax indices to index array B
result = B[argmax_indices]

In [13]:
a = torch.tensor(array_3d)
print(a)
b = torch.topk(a, dim = 2, k=2).indices
b


tensor([[[0.1562, 0.1599, 0.8150, 0.8999],
         [0.3549, 0.1043, 0.4945, 0.7514],
         [0.9733, 0.5753, 0.8862, 0.9275]],

        [[0.8535, 0.2175, 0.8547, 0.5632],
         [0.8717, 0.8389, 0.1295, 0.7818],
         [0.6565, 0.3257, 0.5736, 0.2949]]], dtype=torch.float64)


tensor([[[3, 2],
         [3, 2],
         [0, 3]],

        [[2, 0],
         [0, 1],
         [0, 2]]])

In [14]:
torch.gather(a,2,b)

tensor([[[0.8999, 0.8150],
         [0.7514, 0.4945],
         [0.9733, 0.9275]],

        [[0.8547, 0.8535],
         [0.8717, 0.8389],
         [0.6565, 0.5736]]], dtype=torch.float64)