In [1]:
from PIL import Image
import numpy as np
import torch
# image = np.array(Image.open("images/papillon.jpg"))[:, :, 0]

In [24]:
b, c, a = 2, 3, 4
array_3d = np.random.rand(b, c, a)  # Replace with your actual 3D array
B = np.random.rand(a)  # Replace with your actual array B

# Calculate the argmax along the last axis
argmax_indices = np.argmax(array_3d, axis=2)

# Use the argmax indices to index array B
result = B[argmax_indices]
print(result.shape)

(2, 3)


In [3]:
a = torch.tensor(array_3d)
print(a)
b = torch.topk(a, dim = 2, k=2).indices
b


tensor([[[0.5505, 0.1259, 0.3639, 0.3170],
         [0.9960, 0.9304, 0.0917, 0.4544],
         [0.7787, 0.4785, 0.0523, 0.0591]],

        [[0.3035, 0.7395, 0.5960, 0.0260],
         [0.1674, 0.9564, 0.5492, 0.9243],
         [0.7693, 0.6037, 0.1186, 0.6774]]], dtype=torch.float64)


tensor([[[0, 2],
         [0, 1],
         [0, 1]],

        [[1, 2],
         [1, 3],
         [0, 3]]])

In [4]:
torch.gather(a,2,b)

tensor([[[0.5505, 0.3639],
         [0.9960, 0.9304],
         [0.7787, 0.4785]],

        [[0.7395, 0.5960],
         [0.9564, 0.9243],
         [0.7693, 0.6774]]], dtype=torch.float64)

In [76]:
from coef_chrominance import COEFS
image = torch.randn(size=(1, 3, 64, 64))
print(COEFS.shape)
coefs_to_01 = 2 * COEFS - 1
coefs_a = coefs_to_01[:, 0]
coefs_b = coefs_to_01[:, 1]
coefs_a = coefs_a[None,:,None,None]*torch.ones(1,313,64,64)
ind_max_a = torch.argmax(torch.abs(coefs_a - image[0, 1, :]), dim=1)
coefs_a.gather(1,ind_max_a.unsqueeze(2)).squeeze(2).shape
# coefs_a[ind_max_a].shape
# ind_max_b = torch.argmax(torch.abs(coefs_b - image[:, [2], :]), dim=1)
# ind_max_a.shape
# projected = image.clone()
# print(ind_max_a.shape, coefs_a[ind_max_a].shape)
# projected[:, [1], :, :] = coefs_a[ind_max_a[None,:]]
# projected[:, [2], :, :] = coefs_b[ind_max_b]

torch.Size([313, 2])


tensor([[[[-2.6364, -2.6364, -2.6364,  ..., -2.6364,  0.8182,  0.8182]],

         [[-2.6364, -2.6364,  0.8182,  ..., -2.6364, -2.6364, -2.6364]],

         [[-2.6364, -2.6364, -2.6364,  ..., -2.6364, -2.6364, -2.6364]],

         ...,

         [[-2.6364, -2.6364, -2.6364,  ..., -2.6364, -2.6364, -2.6364]],

         [[ 0.8182, -2.6364, -2.6364,  ..., -2.6364, -2.6364, -2.6364]],

         [[-2.6364, -2.6364,  0.8182,  ..., -2.6364, -2.6364, -2.6364]]]])

In [11]:
coefs_a.permute((0,2,3,1))[ind_max_a]

RuntimeError: [enforce fail at alloc_cpu.cpp:80] data. DefaultCPUAllocator: not enough memory: you tried to allocate 21005074432 bytes.